### ISSUE TITLE
REQUEST: Implementation of WebNowPlaying-Redux with PotPlayer?

### ISSUE THREAD

**Issue by Shikamaru30** [keifufu/WebNowPlaying-Redux#18]
Not sure if you guys are able to do this but it would be awesome if you could. Thanks.

**Comment by keifufu** [comment]
Desktop players are only supported if they can report their media info to Windows, eg: show up in the volume flyout or media control center.
If potplayer does not have this built-in, you can look for plugins to achieve this or ask the developers to add it. It's been a Windows API since the early days of Windows 10 so it's not some obscure api either.
