### ISSUE TITLE
Request: Add "Macro Deck 2 Adapter"

### ISSUE THREAD

**Issue by jbcarreon123** [keifufu/WebNowPlaying-Redux#4]
Name: "Macro Deck 2 Adapter"   
GitHub: https://github.com/jbcarreon123/WebNowPlaying-Redux-Macro-Deck   
Description: It is used for the open-source application "Macro Deck 2" and it will be replacing the outdated and buggy "KSoft.MediaInfo plugin" that Macro Deck has. This will make the formerly requiring 3 plugins to set volume, get song info, and media controls to only 1 plugin. The plugin is coded on .NET Core 3.1.

**Comment by keifufu** [comment]
Thank you for your submission! However, there are a few issues I spotted while flying over your code.

The default seems to open a websocket for legacy communication, where you handle messages and events yourself. I assume it's for spicetify but there are a few things you need to know.
- My recent PR on spicetify-cli ([fix: add compatibility for webnowplaying-redux](https://github.com/spicetify/spicetify-cli/pull/2178)) will make spicetify compatible with WNPReduxAdapterLibrary, so at the very least please only use WNPReduxAdapterLibrary, even if you intend to connect to spicetify.
- Spicetify's current WebNowPlaying extension is only intended to work with the Rainmeter plugin as it can only connect to one port. That port is already taken by WebNowPlaying-Redux-Rainmeter and is not meant to be used by any other adapter. In the future I might create a modern WebNowPlaying-Redux spicetify extension that can connect to multiple adapters, but that's unlikely to happen any time soon.

I also do not see a default port hard-coded anywhere. It seems to be loaded from some config but I can't find the default for that, regardless the port you use should always stay the same, as WebNowPlaying-Redux does not allow users to change the port for official adapters, they are meant to keep the same port in order to guarantee backwards-compatibility with older version of said adapters.

Please also remove any references to WebNowPlaying Companion, or any old names / repo links. The official chrome/firefox webstore listing for what's currently known as WebNowPlaying Companion will update and rename to WebNowPlaying-Redux in the coming days.

**Comment by jbcarreon123** [comment]
The Companion/Spicetify codes are now removed.

**Comment by keifufu** [comment]
Added it to the list of adapters. Will be available once it's updated on the webstore in the coming days.
